### ISSUE TITLE
Nodered 2.2 support?

### ISSUE THREAD

**Issue by logclinker** [simonradier/node-red-contrib-selenium-wd2#16]
Hello,
I'm trying to install this on nodered 2.2.0, and it's failing every time. 

-----------------------------------------------------------
2022-02-17T15:04:47.310Z Install : node-red-contrib-selenium-wd2 0.1.5

2022-02-17T15:04:46.694Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-selenium-wd2@0.1.5
2022-02-17T15:04:50.520Z [err] (node:17518) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
2022-02-17T15:04:50.520Z [err] (Use `node --trace-warnings ...` to show where the warning was created)
2022-02-17T15:04:54.962Z [err] npm
2022-02-17T15:04:54.962Z [err]  
2022-02-17T15:04:54.962Z [err] ERR!
2022-02-17T15:04:54.962Z [err]  
2022-02-17T15:04:54.962Z [err] code
2022-02-17T15:04:54.962Z [err]  1
2022-02-17T15:04:54.962Z [err] npm
2022-02-17T15:04:54.963Z [err]  
2022-02-17T15:04:54.963Z [err] ERR!
2022-02-17T15:04:54.963Z [err]  
2022-02-17T15:04:54.963Z [err] path
2022-02-17T15:04:54.963Z [err]  /home/user/.node-red/node_modules/node-red-contrib-selenium-wd2
2022-02-17T15:04:54.965Z [err] npm
2022-02-17T15:04:54.965Z [err]  
2022-02-17T15:04:54.965Z [err] ERR!
2022-02-17T15:04:54.966Z [err]  command failed
2022-02-17T15:04:54.966Z [err] npm
2022-02-17T15:04:54.966Z [err]  
2022-02-17T15:04:54.966Z [err] ERR!
2022-02-17T15:04:54.966Z [err]  
2022-02-17T15:04:54.966Z [err] command
2022-02-17T15:04:54.966Z [err]  sh -c cp ./patch/http.js ./node_modules/selenium-webdriver/lib/
2022-02-17T15:04:54.966Z [err] npm
2022-02-17T15:04:54.966Z [err]  
2022-02-17T15:04:54.966Z [err] ERR!
2022-02-17T15:04:54.966Z [err]  cp: cannot create regular file './node_modules/selenium-webdriver/lib/': No such file or directory
2022-02-17T15:04:54.967Z [err] 
2022-02-17T15:04:54.967Z [err] npm
2022-02-17T15:04:54.967Z [err]  
2022-02-17T15:04:54.968Z [err] ERR!
2022-02-17T15:04:54.968Z [err]  A complete log of this run can be found in:
2022-02-17T15:04:54.968Z [err] npm
2022-02-17T15:04:54.968Z [err]  
2022-02-17T15:04:54.968Z [err] ERR!
2022-02-17T15:04:54.968Z [err]      /home/user/.npm/_logs/2022-02-17T15_04_46_863Z-debug-0.log
2022-02-17T15:04:54.978Z rc=1

**Comment by simonradier** [comment]
Hi,

Sorry for the late reply. I pushed an update. It should work. Can you confirm it?

Best regards,

**Comment by ahakobyan79** [comment]
After updating, now in one of my flows where I'm trying to click a button, the node gives this error out:

**Comment by logclinker** [comment]
Tried to install again, this time I got this:

Error: set-attribute already registered (line:17)

not sure if this might be because of previous installation or not.

**Comment by simonradier** [comment]
Hi @ahakobyan79 : Have you tried a clean install? Can you tell me with OS you are using?

**Comment by logclinker** [comment]
It's hard to make a clean install, which means I'd have to remove all my nodes. So I can't really test a clean install yet.
I am currently running Node-Red 2.2.0 on Debian 10
After I updated your script to version 0.1.6, this is what happened:
In flows, which were working fine before, I started getting the following Error, on the "Navigate" node, for some reason

"TypeError: Cannot read property 'send' of undefined"

I tried deleting the Navigation node and re-adding it again, that didn't help. 
On one of the flows I had to remove the whole flow, and recreate it again, it worked after that.
On the second flow, i'm unable to make this work.

Do you know what might have caused this?

**Comment by logclinker** [comment]
This is the error i'm getting with 0.1.6 version
```
TypeError: Cannot read property 'send' of undefined
    at Executor.execute (/home/node-red/.node-red/node_modules/node-red-contrib-selenium-wd2/node_modules/selenium-webdriver/lib/http.js:487:33)
    at thenableWebDriverProxy.execute (/home/node-red/.node-red/node_modules/node-red-contrib-selenium-wd2/node_modules/selenium-webdriver/lib/webdriver.js:700:38)
```

**Comment by simonradier** [comment]
It seems there are more regressions than I thought. I'm sorry, I miss some time at the moment to do the check :/. I'm working on a 0.2.x branch which bring lots of improvement, but not sure I can deliver something before summer. You can try https://flows.nodered.org/node/node-red-contrib-wdio which deliver the same type of feature.
I'll keep you in touch when the new version is deliverd.

Regards

**Comment by simonradier** [comment]
Hi @ahakobyan79,

As promised, I updated the package (which as a new name because I switched to another webdriver implementation). Could you tell me if it works on your side?

Best regards,
